version: "3.5"
services:
  nats1-1:
    image: nats
    ports:
      - "8222:8222"
    networks: 
      - nats1-network
    command: -c /conf/server.conf
    volumes:
      - ./conf/c1/server1:/conf
  nats1-2:
    image: nats
    networks: 
      - nats1-network
    depends_on: ["nats1-1"]
    command: -c /conf/server.conf
    volumes:
      - ./conf/c1/server2:/conf
  nats1-3:
    image: nats
    networks: 
      - nats1-network
    depends_on: ["nats1-2"]
    command: -c /conf/server.conf
    volumes:
      - ./conf/c1/server3:/conf

networks:
  nats1-network:
    name: nats

